---
title: "HiDecon benchmarking"
author: "Penghui Huang"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Source Functions

```{r}
source("HiDecon all fun.R")
```

## FHS data 

```{r}
load("data/PBMC/wbc_ref.RData")
cell_type <- ref_list$lm22$meta_ref$deconv_clust

B1 <- rep(1,2)
B2 <- matrix(data = c(1,rep(0,4),rep(1,3)),nrow = 2,byrow = T)
B = list(B1,B2)

load("fhs/fhs_expr_pheno.rdata")
fhs_true <- readRDS("data/FHS/fhs_true.rds")
```

```{r}
FHS_cvres <- cv_HiDecon(bulk = 2^expr-1,ref = ref_list$lm22$ref_matrix, B = B, cell_type = cell_type, type_order = c("lymphocytes", "eosinophils","monocytes","neutrophils"), 
                       lambda.set = seq(10,200,10), Pi.start=NULL, max.iter=1e4, tol=1e-6, 
                       test = "wilcox", nmrk = 50, seed = 123)
HiDecon_est <- FHS_cvres$cv_res
colnames(HiDecon_est) <-  c("lymphocytes", "eosinophils","monocytes","neutrophils")
HiDecon_est
```





## COVID-19 simulation

```{r}
load(file = "COVID19 Ren data/ren.ref.subtypelymph.allseverity2.RData")
cell_type <- rep(c("B_1", "CD4_1",  "B_2" , "CD8_1", "B_3" , "CD8_5", "CD8_7" , "NK_1", "Mono" ,"DC"),126)
load("COVID19 Ren data/naturemix sublymph all severity2.RData")
colnames(naturemix$true.frac) <- c("B_1", "CD4_1",  "B_2" , "CD8_1", "B_3" , "CD8_5", "CD8_7" , "NK_1", "Mono" ,"DC", "severity")
naturemix$true.frac <- naturemix$true.frac[,c("Mono", "DC", "B_1", "B_2", "B_3","NK_1","CD4_1", "CD8_1", "CD8_5", "CD8_7", "severity")]
```

```{r}
B1 <- rep(1,2)
B2 <- matrix(c(1,1,0,0,0,0,1,1),nrow = 2, byrow = T)
B3 <- matrix(c(1,rep(0,5),1,rep(0,5),1,rep(0,5),1,1),nrow = 4, byrow = T)
B4 <- matrix(c(1,rep(0,6),1,rep(0,6),1,rep(0,6),1,rep(0,6),1,1),nrow = 5, byrow = T)
B5 <- matrix(c(1,1,1,rep(0,12), 1, rep(0,12), 1,1,1, rep(0,12),1,rep(0,12),1,rep(0,12),1,1,1 ), nrow = 6, byrow=T)
B = list(B1,B2,B3,B4,B5)
B[[5]] <- cbind(c(1,0,0,0,0,0),((B[[5]])[,4:12])) 
```


```{r}
system.time(COVIDsub_cvres <- cv_HiDecon(bulk = naturemix$bulk, ref = ren.ref, B = B, cell_type = cell_type, type_order = c("Mono", "DC", "B_1", "B_2", "B_3","NK_1","CD4_1", "CD8_1", "CD8_5", "CD8_7"), 
                       lambda.set = seq(10,200,10), Pi.start=NULL, max.iter=1e4, tol=1e-6, 
                       test = "wilcox", nmrk = 50, seed = 123))
```

```{r}
real_prop <- naturemix$true.frac
real_prop <- real_prop[,c("Mono", "DC", "B_1", "B_2", "B_3","NK_1","CD4_1", "CD8_1", "CD8_5", "CD8_7")]
```